name: Drupal Code Checker PR

on: 
    pull_request:
        branches: master

jobs:
    code-checker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run: actions/checkout@v3
              
            - name: Setup PHP
              uses: shivammatur/setup-php@v2
              with:
                php-version: '8.1'
                coverage: none
                tools: composer, cs2pr
                
            - name: Get Composer cache directory
              id: composer-cahe
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
                    
            - name: Install dependecies
              run:  composer install --prefer-dist --no-suggest --no-progress
              
            - name: Detect coding standard violations
              run: vendor/bin/phpcs -q --report=checkstyle | cs2pr --graceful-warnings  
              
